version: '3.9'

services:
  db:
    image: 'postgres'
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    env_file: ./.env
    ports:
      - '5432:5432'
    networks:
      - text-network

  app:
    image: 2e0942b273f6
    ports:
      - '8080:8080'
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_URL=jdbc:postgresql://db:5432/postgres
    env_file: ./.env
    depends_on:
      - db
    networks:
      - text-network

networks:
  text-network:
    driver: bridge
